// GENERATED by scripts/build-kb.mjs from pillser.com - do not edit by hand. Refresh: npm run kb:build

export default {
  "source": "Pillser",
  "source_url": "https://pillser.com/health-outcomes",
  "generated_at": "2026-07-08T10:22:22.731Z",
  "outcomes": {
    "increased-hdl-cholesterol-levels": {
      "title": "Increased HDL cholesterol levels",
      "url": "https://pillser.com/health-outcomes/increased-hdl-cholesterol-levels",
      "study_count": 11
    },
    "reduced-ldl-cholesterol-levels": {
      "title": "Reduced LDL cholesterol levels",
      "url": "https://pillser.com/health-outcomes/reduced-ldl-cholesterol-levels",
      "study_count": 26
    },
    "reduced-triglycerides": {
      "title": "Reduced triglycerides",
      "url": "https://pillser.com/health-outcomes/reduced-triglycerides",
      "study_count": null
    },
    "improved-insulin-sensitivity": {
      "title": "Improved insulin sensitivity",
      "url": "https://pillser.com/health-outcomes/improved-insulin-sensitivity",
      "study_count": 1119
    },
    "reduced-blood-glucose-levels": {
      "title": "Reduced blood glucose levels",
      "url": "https://pillser.com/health-outcomes/reduced-blood-glucose-levels",
      "study_count": 17
    },
    "reduced-inflammation": {
      "title": "Reduced inflammation",
      "url": "https://pillser.com/health-outcomes/reduced-inflammation",
      "study_count": 69
    },
    "reduced-blood-pressure": {
      "title": "Reduced blood pressure",
      "url": "https://pillser.com/health-outcomes/reduced-blood-pressure",
      "study_count": 11
    },
    "reduced-body-weight": {
      "title": "Reduced body weight",
      "url": "https://pillser.com/health-outcomes/reduced-body-weight",
      "study_count": 30
    },
    "improved-sleep-quality": {
      "title": "Improved sleep quality",
      "url": "https://pillser.com/health-outcomes/improved-sleep-quality",
      "study_count": 12
    },
    "reduced-uric-acid-levels": {
      "title": "Reduced uric acid levels",
      "url": "https://pillser.com/health-outcomes/reduced-uric-acid-levels",
      "study_count": 3
    },
    "increased-testosterone-levels": {
      "title": "Increased testosterone levels",
      "url": "https://pillser.com/health-outcomes/increased-testosterone-levels",
      "study_count": 4
    },
    "reduced-homocysteine-levels": {
      "title": "Reduced homocysteine levels",
      "url": "https://pillser.com/health-outcomes/reduced-homocysteine-levels",
      "study_count": 6
    }
  }
};
